require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

RSpec/NestedGroups:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/LineLength:
  Max: 150

Lint/MissingCopEnableDirective:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false
