AllCops:
  TargetRubyVersion: 2.4

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 130

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/FileName:
  Enabled: false

Documentation:
  Enabled: false
